---
title: "Exploratory Data Analysis"
author: "Min-Yao"
date: "2017年5月21日"
output: 
  html_document: 
    keep_md: yes
---

# 7 Exploratory Data Analysis

## 7.1 Introduction

### 7.1.1 Prerequisites

```{r}
library(tidyverse)
```

## 7.2 Questions

## 7.3 Variation

### 7.3.1 Visualising distributions

```{r}
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut))

diamonds %>% 
  count(cut)

ggplot(data = diamonds) +
  geom_histogram(mapping = aes(x = carat), binwidth = 0.5)

diamonds %>% 
  count(cut_width(carat, 0.5))

smaller <- diamonds %>% 
  filter(carat < 3)
  
ggplot(data = smaller, mapping = aes(x = carat)) +
  geom_histogram(binwidth = 0.1)

ggplot(data = smaller, mapping = aes(x = carat, colour = cut)) +
  geom_freqpoly(binwidth = 0.1)

```


### 7.3.2 Typical values

```{r}
ggplot(data = smaller, mapping = aes(x = carat)) +
  geom_histogram(binwidth = 0.01)

ggplot(data = faithful, mapping = aes(x = eruptions)) + 
  geom_histogram(binwidth = 0.25)


```


### 7.3.3 Unusual values

```{r}
ggplot(diamonds) + 
  geom_histogram(mapping = aes(x = y), binwidth = 0.5)

ggplot(diamonds) + 
  geom_histogram(mapping = aes(x = y), binwidth = 0.5) +
  coord_cartesian(ylim = c(0, 50))

unusual <- diamonds %>% 
  filter(y < 3 | y > 20) %>% 
  select(price, x, y, z) %>%
  arrange(y)
unusual

```


### 7.3.4 Exercises

## 7.4 Missing values

### 7.4.1 Exercises

## 7.5 Covariation

### 7.5.1 A categorical and continuous variable

#### 7.5.1.1 Exercises

### 7.5.2 Two categorical variables

#### 7.5.2.1 Exercises

### 7.5.3 Two continuous variables

#### 7.5.3.1 Exercises


